version: "2.3"
services:
  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    restart: always
    ports:
     - "3306:3306"
  
  backend:
    build: ./backend
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: on-failure

  frontend:
    build: ./frontend
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
    ports:
      - "8100:8100"
    restart: on-failure
