version: "2.3"
services:
  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    restart: always
    ports:
     - "3306:3306"
  web:
    build: ./web
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: on-failure
